<a href="https://colab.research.google.com/github/venkat032/machine-learning-/blob/main/py2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data={'age':[20,25,24,27,40,45],'exp':[1,2,3.5,5,4.5,3.6],'ab':[100000,200000,300000,400000,500000,600000],'salary':[10000,20000,25000,30000,35000,40000]}
df=pd.DataFrame(data)
df.head()

age  exp      ab  salary
0   20  1.0  100000   10000
1   25  2.0  200000   20000
2   24  3.5  300000   25000
3   27  5.0  400000   30000
4   40  4.5  500000   35000

In [ ]:
from sklearn.preprocessing import StandardScaler
x=df[['age','exp','ab']]
standard=StandardScaler()
x_scaled=StandardScaler().fit_transform(x)
x_scaled

array([[-1.11950165, -1.64201398, -1.46385011],
       [-0.56892707, -0.91759605, -0.87831007],
       [-0.67904198,  0.16903085, -0.29277002],
       [-0.34869723,  1.25565775,  0.29277002],
       [ 1.08279667,  0.89344878,  0.87831007],
       [ 1.63337125,  0.24147264,  1.46385011]])

In [ ]:
df=pd.read_csv('/content/standard_scaler_dataset.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/standard_scaler_dataset.csv'

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(df['Age'],df['Salary'])
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x=df[['Age','Experience']]
y=df['Salary']
standard=StandardScaler()
x_scaled=StandardScaler().fit_transform(x)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x_scaled)
xtrain,xtest,ytrain,ytest=train_test_split(x_poly,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
r2_score(ytest,pred)

In [ ]:
pred1=model.predict(xtrain)
r2_score(ytrain,pred1)

In [ ]:
df=pd.read_csv('/content/predicting_employee_productivity.csv')
df.head()

In [ ]:
x=df[['Weekly_Work_Hours','Stress_Level_Score']]
y=df['Productivity_Score']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
standard=StandardScaler()
x_scaled=StandardScaler().fit_transform(x)
x_scaled

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x_scaled)
xtrain,xtest,ytrain,ytest=train_test_split(x_poly,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
r2_score(ytest,pred)


In [ ]:
pred2=model.predict(xtrain)
r2_score(ytrain,pred2)

In [ ]:
df=pd.read_csv('/content/standardscaler 2.csv')
df.head()

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(df['Feature3'],df['Target'])
plt.show()

In [ ]:
x=df[['Feature1','Feature2','Feature3']]
y=df['Target']
standard=StandardScaler()
x_scaled=StandardScaler().fit_transform(x)
x_scaled

In [ ]:
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x_scaled)
xtrain,xtest,ytrain,ytest=train_test_split(x_poly,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
r2_score(ytest,pred)

In [ ]:
pred1=model.predict(xtrain)
r2_score(ytrain,pred1)

In [ ]:
data = {'Age':[25,30,35,40,45,10,20,50,47,16],'edu_level':list(range(1,11)),'Loan':[1,1,1,1,1,0,0,1,1,0]}
df=pd.DataFrame(data)
x=df[['Age','edu_level']]
y=df['Loan']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
pred

In [ ]:
newinputs=pd.DataFrame({'Age':[43,18,56],'edu_level':[3,1,6]})
pred=model.predict(newinputs)
pred

In [ ]:
df=pd.DataFrame({'Mail':['you selected as data analyst xxx company','1cr credited to your account xxxx990390','click this link to win an iphone'],'abc':['sndnf','nfnvnv','fbkbjv'],'result':[1,0,0]})
df

In [ ]:
x=df['Mail']
x1=df['abc']
df['combined']=df['Mail']+' '+df['abc']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
updated_x=tfidf.fit_transform(df['combined'])
updated_x.toarray()
#----------------------------------
#tfidf1=TfidfVectorizer()
#updated_x1=tfidf1.fit_transform(x1)
#udated1_x1.toarray()
model=LogisticRegression()
model.fit(updated_x,df['result'])
pred=model.predict(updated_x)
pred

In [ ]:
newinputs=['you selected as data analyst xxx company','sndnf']
newinputs=[' '.join(newinputs)]
transform=tfidf.transform(newinputs)
transform.toarray
pred=model.predict(transform)
pred

In [ ]:
x=['Data science is fun','I Love Data science','Science is amazing']


In [ ]:
df=pd.DataFrame({'Data':[0.25,0.25,0],'Science':[0.25,0.25,0.33],'is':[0.25,0,0.33],'fun':[0.25,0,0],'I':[0,0.25,0],'Love':[0,0.25,0],'amazing':[0,0,0.33]})
df

In [ ]:
import pandas as pd
df=pd.read_csv('/content/logistic_regression_dataset.csv')
df.head()


Review     Category    Rating
0   Not as expected, disappointed        Books  Negative
1   Fantastic! Highly recommended     Clothing  Negative
2  Great features and easy to use     Clothing  Negative
3       Horrible, do not buy this  Electronics  Positive
4   Fantastic! Highly recommended         Home  Positive

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
label=LabelEncoder()
label1=LabelEncoder()
df['label_category']=label.fit_transform(df['Category'])
df['label_rating']=label1.fit_transform(df['Rating'])
df['Category'].unique()
df.head()

Review     Category    Rating  label_category  \
0   Not as expected, disappointed        Books  Negative               0   
1   Fantastic! Highly recommended     Clothing  Negative               1   
2  Great features and easy to use     Clothing  Negative               1   
3       Horrible, do not buy this  Electronics  Positive               2   
4   Fantastic! Highly recommended         Home  Positive               3   

   label_rating  
0             0  
1             0  
2             0  
3             1  
4             1

In [ ]:
x=df[['label_category']]
y=df['Rating']
model=LogisticRegression()
model.fit(x,y)
new_inputs=['Books']
new_inputs=label.transform(new_inputs)
new_inputs=new_inputs.reshape(-1,1)
pred=model.predict(new_inputs)
pred

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Negative'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import pandas as pd
df=pd.read_csv('/content/logistic_regression_dataset.csv')

vectorizer=TfidfVectorizer()
label=LabelEncoder()
x_review = vectorizer.fit_transform(df['Review'])

x_independent=pd.DataFrame(x_review.toarray(),columns=vectorizer.get_feature_names_out())
x_independent['label_category']=label.fit_transform(df['Category'])
y=df['Rating']

xtrain,xtest,ytrain,ytest=train_test_split(x_independent,y,test_size=0.2,random_state=42)
model=LogisticRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
confusion_matrix(ytest,pred,labels=['Positive','Negative'])


array([[7, 4],
       [6, 3]])

In [ ]:
precision_score(ytest,pred,pos_label='Positive')
precision_score(ytest,pred,pos_label='Negative')

0.42857142857142855

In [ ]:
recall_score(ytest,pred,pos_label='Positive')
recall_score(ytest,pred,pos_label='Negative')

0.3333333333333333

In [ ]:
d = {'Review':['Not as expected, disappointed','Fantastic! Highly recommended'],'Category':['Books','Clothing']}
new_review=vectorizer.transform(d['Review'])
newinp=pd.DataFrame(new_review.toarray(),columns=vectorizer.get_feature_names_out())
newinp['label_category']=label.transform(d['Category'])
pred=model.predict(newinp)
pred

array(['Negative', 'Positive'], dtype=object)

In [ ]:
df=pd.read_csv('/content/large_sample_sentiment.csv')
df.head()

text       category     label
0       Would not recommend.           Food  negative
1       Would not recommend.    Electronics  negative
2          Horrible quality.           Tech  negative
3    I absolutely love this!        Service  positive
4  Exceeded my expectations!  Entertainment  positive

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import recall_score
vectorizer=TfidfVectorizer()
label=LabelEncoder()
x=vectorizer.fit_transform(df['label'])
x_independent=pd.DataFrame(x.toarray(),columns=vectorizer.get_feature_names_out())
x_independent['label_category']=label.fit_transform(df['category'])
y=df['label']
xtrain,xtest,ytrain,ytest=train_test_split(x_independent,y,test_size=0.2,random_state=42)
model=LogisticRegression()
model.fit(xtrain,ytrain)
pred=model.predict(xtest)
confusion_matrix(ytest,pred,labels=['positive','negative'])


array([[ 98,   0],
       [  0, 102]])

In [ ]:
recall_score(ytest,pred,pos_label='positive')
recall_score(ytest,pred,pos_label='negative')

1.0

In [ ]:
precision_score(ytest,pred,pos_label='positive')
precision_score(ytest,pred,pos_label='negative')

1.0

In [ ]:
data = {'text':['Extremely frustrating','This made my day!'],'category':['Review','Electronics']}
new_rew=vectorizer.transform(data['text'])
newinputs=pd.DataFrame(new_rew.toarray(),columns=vectorizer.get_feature_names_out())
newinputs['label_category']=label.transform(data['category'])
pred=model.predict(newinputs)
pred



array(['negative', 'negative'], dtype=object)